### ISSUE TITLE
package.json is not present

### ISSUE THREAD

**Issue by JulianH99** [Errec/MyWebDevBoilerplate#1]
It would be easier to use the repo if you provided the package.json instead of installing all the dependencies  one by one

**Comment by Tazaf** [comment]
Especially since the `gulpfile.js` uses `gulp.start()` which is no more supported by the latest version of Gulp (4.x), thus raising an error when executing `gulp setup`.

Using a `package.json` file would lock the Gulp version to one that is compatible with the provided `gulpfile.js`.

**Comment by Errec** [comment]
Fixed on branch v2
